name: Playlist-Generator workflow
on:
  schedule:
    - cron: "* * * * *"  # This will run at 00:00 UTC every day
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run updater script
        run: |
          pip3 install -r requirements.txt
          python3 main.py
      - name: Commit playlists
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add playlists
          git commit -m "Updated via AutoBot 🤖" || echo "No changes to commit"
          git push
